import type { Tool } from '@/lib/types'

export const tools: Tool[] = [
  // ── LIVE ──────────────────────────────────────────────────────────────────
  {
    slug: 'rainwater',
    href: '/tools/rainwater',
    label: 'Rainwater Harvest Calculator',
    blurb: 'How much water you can capture from your roof, by month. Pick your conditions, get the answer, and see what size cistern actually makes sense for your setup.',
    category: 'water',
    bucket: 'build',
    status: 'live',
    num: '01 · Water',
    photo: '/photos/rainbarrel_filling.jpg',
    featured: true,
    intents: ['collect rainwater', 'rain barrel', 'cistern', 'catch water off my roof', 'water my garden'],
  },
  {
    slug: 'seed-starting',
    href: '/tools/seed-starting',
    label: 'Seed Starting Calendar',
    blurb: 'Back out from your last frost date. Honest about the margin.',
    category: 'planting',
    bucket: 'plan',
    status: 'live',
    num: '02 · Timing',
    photo: '/photos/seed-starting.jpg',
    intents: ['start seeds', 'when to plant', 'seed timing', 'indoor sowing'],
  },
  {
    slug: 'mulch',
    href: '/tools/mulch',
    label: 'Mulch Calculator',
    blurb: 'Cubic yards by bed. Bags versus bulk, settled.',
    category: 'soil',
    bucket: 'grow',
    status: 'live',
    num: '03 · Soil',
    photo: '/photos/mulch.jpg',
    gradient: 'soil',
    intents: ['mulch', 'cover the soil', 'retain moisture', 'suppress weeds'],
  },
  {
    slug: 'square-foot',
    href: '/tools/square-foot',
    label: 'Square Foot Planner',
    blurb: 'What fits where, without the spreadsheet headache.',
    category: 'planting',
    bucket: 'plan',
    status: 'live',
    num: '04 · Planning',
    photo: '/photos/square-foot.jpg',
    intents: ['lay out a bed', 'plan spacing', 'what fits where', 'garden layout'],
  },
  {
    slug: 'soil-volume',
    href: '/tools/soil-volume',
    label: 'Soil Volume Calculator',
    blurb: 'How much soil fills the bed. Cubic feet, cubic yards, bags to buy.',
    category: 'soil',
    bucket: 'build',
    status: 'live',
    num: '05 · Soil',
    photo: '/photos/soil.jpg',
    gradient: 'soil',
    intents: ['fill a raised bed', 'how much soil', 'bags of soil'],
  },
  {
    slug: 'frost-dates',
    href: '/tools/frost-dates',
    label: 'Frost Date Planner',
    blurb: 'First and last frost by your location. The calendar that actually matters.',
    category: 'planting',
    bucket: 'plan',
    status: 'live',
    num: '06 · Timing',
    photo: '/photos/frost.jpg',
    gradient: 'timing',
    intents: ['frost dates', 'protect from frost', 'when is it safe to plant', 'growing season length'],
  },

  // ── COMING SOON ───────────────────────────────────────────────────────────
  {
    slug: 'compost-ratio',
    href: '/tools/compost-ratio',
    label: 'Compost Ratio Calculator',
    blurb: 'Browns and greens, worked out so the pile actually heats up.',
    category: 'soil',
    bucket: 'grow',
    status: 'live',
    num: '07 · Soil',
    photo: '/photos/compost.jpg',
    intents: ['compost', 'browns and greens', 'reduce kitchen waste', 'hot compost'],
  },
  {
    slug: 'sun-calculator',
    href: '/tools/sun-calculator',
    label: 'Sun Calculator',
    blurb: 'Hours of direct sun. Plants that want exactly that.',
    category: 'planning',
    bucket: 'plan',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/sunflower.jpg',
    intents: ['how much sun', 'full sun or shade', 'sunlight hours'],
  },
  {
    slug: 'seed-spacing',
    href: '/tools/seed-spacing',
    label: 'Seed Spacing & Yield',
    blurb: 'Plant count plus a rough harvest estimate for a row or bed.',
    category: 'planting',
    bucket: 'plan',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/yield.jpg',
    intents: ['how many plants', 'spacing', 'estimate my harvest'],
  },
  {
    slug: 'moon-phase',
    href: '/tools/moon-phase',
    label: 'Moon Phase Planting',
    blurb: 'No scientific basis. Big search volume. Included for completeness.',
    category: 'misc',
    bucket: 'plan',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/moon.png',
    gradient: 'planning',
    intents: ['plant by the moon', 'moon phase'],
  },

  // ── ON THE HORIZON ────────────────────────────────────────────────────────
  {
    slug: 'companion-matrix',
    href: '/tools/companion-matrix',
    label: 'Companion Planting Matrix',
    blurb: 'The researched version, not the Pinterest version.',
    category: 'planting',
    bucket: 'plan',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/companion-planting.jpg',
    intents: ['companion planting', 'what grows well together'],
  },
  {
    slug: 'pest-id',
    href: '/tools/pest-id',
    label: 'Pest ID & Response',
    blurb: 'Identify the pest. Know the response.',
    category: 'misc',
    bucket: 'grow',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/sick-cucumber.jpg',
    intents: ['identify a pest', 'bugs on my plants', 'deal with pests', 'what is eating my plants'],
  },
  {
    slug: 'drip',
    href: '/tools/drip',
    label: 'Drip Irrigation Planner',
    blurb: 'Emitter count, gallons per hour, run time per bed.',
    category: 'water',
    bucket: 'build',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/drip_irrigation.jpg',
    gradient: 'water',
    intents: ['irrigate my garden', 'drip irrigation', 'watering system', 'automatic watering'],
  },
  {
    slug: 'trellis',
    href: '/tools/trellis',
    label: 'Trellis Selector',
    blurb: 'By crop, height, weight load.',
    category: 'structure',
    bucket: 'build',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/trellis.jpg',
    gradient: 'planning',
    intents: ['build a trellis', 'grow vertically', 'support climbing plants'],
  },
  {
    slug: 'hugelkultur',
    href: '/tools/hugelkultur',
    label: 'Hugelkultur Calculator',
    blurb: 'Wood, soil, compost ratios for a mound bed.',
    category: 'soil',
    bucket: 'build',
    status: 'live',
    num: '09 · Soil',
    photo: '/photos/hugelkultur.jpg',
    gradient: 'soil',
    intents: ['build a mound bed', 'hugelkultur', 'bury wood'],
  },
  {
    slug: 'worm-bin',
    href: '/tools/worm-bin',
    label: 'Worm Bin Sizer',
    blurb: 'Household size to bin size to feeding rate.',
    category: 'soil',
    bucket: 'grow',
    status: 'live',
    num: '08 · Soil',
    photo: '/photos/worms.jpg',
    gradient: 'soil',
    intents: ['vermicompost', 'worms', 'compost indoors', 'reduce kitchen waste'],
  },
]
