import type { Tool } from '@/lib/types'

export const tools: Tool[] = [
  // ── LIVE ──────────────────────────────────────────────────────────────────
  {
    slug: 'rainwater',
    href: '/tools/rainwater',
    label: 'Rainwater Harvest Calculator',
    blurb: 'How much water you can capture from your roof, by month. Pick your conditions, get the answer, and see what size cistern actually makes sense for your setup.',
    category: 'water',
    status: 'live',
    num: '01 · Water',
    photo: '/photos/rainbarrel_filling.jpg',
    featured: true,
  },
  {
    slug: 'seed-starting',
    href: '/tools/seed-starting',
    label: 'Seed Starting Calendar',
    blurb: 'Back out from your last frost date. Honest about the margin.',
    category: 'planting',
    status: 'live',
    num: '02 · Timing',
    photo: '/photos/seed-starting.jpg',
  },
  {
    slug: 'mulch',
    href: '/tools/mulch',
    label: 'Mulch Calculator',
    blurb: 'Cubic yards by bed. Bags versus bulk, settled.',
    category: 'soil',
    status: 'live',
    num: '03 · Soil',
    photo: '/photos/mulch.jpg',
    gradient: 'soil',
  },
  {
    slug: 'square-foot',
    href: '/tools/square-foot',
    label: 'Square Foot Planner',
    blurb: 'What fits where, without the spreadsheet headache.',
    category: 'planting',
    status: 'live',
    num: '04 · Planning',
    photo: '/photos/square-foot.jpg',
  },
  {
    slug: 'soil-volume',
    href: '/tools/soil-volume',
    label: 'Soil Volume Calculator',
    blurb: 'How much soil fills the bed. Cubic feet, cubic yards, bags to buy.',
    category: 'soil',
    status: 'live',
    num: '05 · Soil',
    gradient: 'soil',
  },
  {
    slug: 'frost-dates',
    href: '/tools/frost-dates',
    label: 'Frost Date Planner',
    blurb: 'First and last frost by your location. The calendar that actually matters.',
    category: 'planting',
    status: 'live',
    num: '06 · Timing',
    photo: '/photos/frost.jpg',
    gradient: 'timing',
  },

  // ── COMING SOON ───────────────────────────────────────────────────────────
  {
    slug: 'compost-ratio',
    href: '/tools/compost-ratio',
    label: 'Compost Ratio Calculator',
    blurb: 'Browns and greens, worked out so the pile actually heats up.',
    category: 'soil',
    status: 'live',
    num: '07 · Soil',
    photo: '/photos/compost.jpg',
  },
  {
    slug: 'soil-recipes',
    href: '/tools/soil-recipes',
    label: 'Soil Recipes',
    blurb: 'Seed-starting mix, potting mix, raised-bed fill. Ratios scaled to volume.',
    category: 'soil',
    status: 'soon',
    num: 'Coming Soon',
    gradient: 'soil',
  },
  {
    slug: 'sun-calculator',
    href: '/tools/sun-calculator',
    label: 'Sun Calculator',
    blurb: 'Hours of direct sun. Plants that want exactly that.',
    category: 'planning',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/sunflower.jpg',
  },
  {
    slug: 'seed-spacing',
    href: '/tools/seed-spacing',
    label: 'Seed Spacing & Yield',
    blurb: 'Plant count plus a rough harvest estimate for a row or bed.',
    category: 'planting',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/yield.jpg',
  },
  {
    slug: 'moon-phase',
    href: '/tools/moon-phase',
    label: 'Moon Phase Planting',
    blurb: 'No scientific basis. Big search volume. Included for completeness.',
    category: 'misc',
    status: 'soon',
    num: 'Coming Soon',
    photo: '/photos/moon.png',
    gradient: 'planning',
  },
  {
    slug: 'solar-sizer',
    href: '/tools/solar-sizer',
    label: 'Solar Panel Sizer',
    blurb: 'Greenhouse, shed, chicken coop. Panels for what you actually run.',
    category: 'structure',
    status: 'soon',
    num: 'Coming Soon',
    gradient: 'planning',
  },

  // ── ON THE HORIZON ────────────────────────────────────────────────────────
  {
    slug: 'companion-matrix',
    href: '/tools/companion-matrix',
    label: 'Companion Planting Matrix',
    blurb: 'The researched version, not the Pinterest version.',
    category: 'planting',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/companion-planting.jpg',
  },
  {
    slug: 'pest-id',
    href: '/tools/pest-id',
    label: 'Pest ID & Response',
    blurb: 'Identify the pest. Know the response.',
    category: 'misc',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/sick-cucumber.jpg',
  },
  {
    slug: 'crop-rotation',
    href: '/tools/crop-rotation',
    label: 'Crop Rotation Planner',
    blurb: 'Three- or four-year rotation by plant family.',
    category: 'planning',
    status: 'horizon',
    num: 'Planned',
    gradient: 'planning',
  },
  {
    slug: 'cover-crop',
    href: '/tools/cover-crop',
    label: 'Cover Crop Selector',
    blurb: 'By goal: nitrogen-fixing, weed suppression, compaction.',
    category: 'planting',
    status: 'horizon',
    num: 'Planned',
    gradient: 'planning',
  },
  {
    slug: 'drip',
    href: '/tools/drip',
    label: 'Drip Irrigation Planner',
    blurb: 'Emitter count, gallons per hour, run time per bed.',
    category: 'water',
    status: 'horizon',
    num: 'Planned',
    gradient: 'water',
  },
  {
    slug: 'greenhouse-heat',
    href: '/tools/greenhouse-heat',
    label: 'Greenhouse Heating Load',
    blurb: 'Square footage, target temp, climate input. BTUs out.',
    category: 'structure',
    status: 'horizon',
    num: 'Planned',
    gradient: 'planning',
  },
  {
    slug: 'coop-sizer',
    href: '/tools/coop-sizer',
    label: 'Chicken Coop Sizer',
    blurb: 'Birds per square foot, indoor versus run.',
    category: 'structure',
    status: 'horizon',
    num: 'Planned',
    gradient: 'planning',
  },
  {
    slug: 'trellis',
    href: '/tools/trellis',
    label: 'Trellis Selector',
    blurb: 'By crop, height, weight load.',
    category: 'structure',
    status: 'horizon',
    num: 'Planned',
    photo: '/photos/trellis.jpg',
    gradient: 'planning',
  },
  {
    slug: 'hugelkultur',
    href: '/tools/hugelkultur',
    label: 'Hugelkultur Calculator',
    blurb: 'Wood, soil, compost ratios for a mound bed.',
    category: 'soil',
    status: 'live',
    num: '09 · Soil',
    photo: '/photos/hugelkultur.png',
    gradient: 'soil',
  },
  {
    slug: 'worm-bin',
    href: '/tools/worm-bin',
    label: 'Worm Bin Sizer',
    blurb: 'Household size to bin size to feeding rate.',
    category: 'soil',
    status: 'live',
    num: '08 · Soil',
    gradient: 'soil',
  },
  {
    slug: 'winter-sowing',
    href: '/tools/winter-sowing',
    label: 'Winter Sowing Calendar',
    blurb: 'Milk jug method, by zone.',
    category: 'planting',
    status: 'horizon',
    num: 'Planned',
    gradient: 'timing',
  },
  {
    slug: 'paver',
    href: '/tools/paver',
    label: 'Path & Paver Estimator',
    blurb: 'For brick circles, walkways, and edging.',
    category: 'structure',
    status: 'horizon',
    num: 'Planned',
    gradient: 'planning',
  },
]
